# Generated by Django 4.2.7 on 2025-04-15 07:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0002_initial_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='priority',
        ),
        migrations.AddField(
            model_name='grievance',
            name='ai_category_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='grievance',
            name='ai_priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='grievance',
            name='ai_priority_confidence',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='grievance',
            name='ai_sentiment_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='grievance',
            name='ai_suggested_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grievances/'),
        ),
        migrations.AlterField(
            model_name='grievanceupdate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
