# Generated by Django 4.2.7 on 2025-04-18 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_remove_grievance_priority_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grievance',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='grievance',
            name='category',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('sanitation', 'Sanitation'), ('safety', 'Safety'), ('education', 'Education'), ('health', 'Health'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='GrievanceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='grievance_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('grievance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='grievances.grievance')),
            ],
        ),
    ]
