# Generated by Django 5.2 on 2025-04-19 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "grievances",
            "0004_alter_grievance_options_alter_grievance_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_set",
                related_query_name="custom_user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                related_name="custom_user_set",
                related_query_name="custom_user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AlterField(
            model_name="grievance",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_grievances",
                to="grievances.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="grievance",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_grievances",
                to="grievances.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="grievanceupdate",
            name="updated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="grievances.customuser"
            ),
        ),
    ]
