# Generated by Django 5.2 on 2025-04-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievances", "0006_alter_customuser_options_customuser_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
