# Generated by Django 5.2 on 2025-04-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievances", "0008_alter_grievance_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grievanceattachment",
            name="file",
            field=models.ImageField(upload_to="grievance_attachments/"),
        ),
    ]
