# Generated by Django 5.2 on 2025-04-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("grievances", "0009_alter_grievanceattachment_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="grievance",
            name="is_anonymous",
            field=models.BooleanField(default=False),
        ),
    ]
